name: aspireme_flutter
description: "App to write you quesiont and answer in document form then change it to flashcard at will."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  pulsator: ^1.0.0
  connectivity_plus: ^6.0.5
  flutter_automation: ^2.0.0
  flutter_svg: ^2.0.9
  sqflite: ^2.3.3+1
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  flutter_spinkit: ^5.2.1
  google_sign_in: ^6.2.1
  flutter_launcher_icons: ^0.14.1
  path: any
  tutorial_coach_mark: ^1.2.11
  firebase_core: ^3.5.0 
  rename: ^3.0.2
  firebase_auth: ^5.3.0
  easy_folder_picker: ^1.3.3
  cloud_firestore: ^5.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

  assets:
    - asset/button/
    - asset/Icons/
    
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "asset/app_icon_crop.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21